name: FrozenSilverfish
version: '${version}'
main: dev.ghiacciolo.frozensilverfish.FrozenSilverfish
api-version: '26.2'
description: Removes the AI from silverfish while keeping their physics.
author: ghiacciolodev
website: https://github.com/ghiacciolodev/FrozenSilverfish

commands:
  frozensilverfish:
    description: Manage FrozenSilverfish.
    usage: /<command> <reload|status>
    aliases: [fsf]
    permission: frozensilverfish.admin

permissions:
  frozensilverfish.admin:
    description: Allows using /frozensilverfish.
    default: op
